### ISSUE TITLE
Only INGInious-problems-electrical needed on this repo

### ISSUE THREAD

**Issue by anthonygego** [UCL-INGI/INGInious-problems-electrical#1]
Only the ``INGInious-problems-electrical`` folder content is needed on this repo, as this is the case for other plugins. People on the internet do not need the entire workspace of your master's thesis :-)

Please put a similar ``README.md`` file as well as a ``LICENSE`` file. We typically use AGPL v3.

**Comment by artbil** [comment]
All is clean now :)
